# Generated by Django 4.1.3 on 2022-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField()),
                ('date_activity', models.DateTimeField()),
                ('last_answer', models.DateTimeField()),
                ('num_views', models.IntegerField()),
            ],
        ),
    ]
