# Generated by Django 4.1.3 on 2022-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_date_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='num_likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='num_views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
