# Generated by Django 4.1.3 on 2022-11-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_num_likes_blog_num_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='num_answers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
