# Generated by Django 4.1.3 on 2022-11-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('date_creation', models.DateTimeField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='year.year')),
            ],
        ),
    ]
