# Generated by Django 4.1.3 on 2022-11-23 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_answer',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
