# Generated by Django 4.1.3 on 2022-11-22 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='num_likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
