# Generated by Django 4.1.3 on 2022-12-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_answer_date_creation_answer_num_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='topic',
        ),
    ]
